# Generated by Django 3.0.7 on 2020-07-04 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalPayIdEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentNetwork', models.CharField(max_length=8)),
                ('environment', models.CharField(max_length=12)),
                ('tag', models.CharField(default='primary', max_length=32)),
                ('show', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=128)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payId.LocalPayIdEntity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AchAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentNetwork', models.CharField(max_length=8)),
                ('environment', models.CharField(max_length=12)),
                ('tag', models.CharField(default='primary', max_length=32)),
                ('show', models.BooleanField(default=True)),
                ('accountNumber', models.CharField(max_length=16)),
                ('routingNumber', models.CharField(max_length=40)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payId.LocalPayIdEntity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
